# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'SocialShareDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app
	pod 'SocialShare', :path => '/Users/shashanksingh/Documents/iOSUtils'

end